### PR TITLE
add tmp dir mount everywhere

### PR DESCRIPTION
**Pull request by monotek**
#### What this PR does / why we need it

- add tmp dir mount everywhere
- update zammad to 6.0.0-76

#### Which issue this PR fixes

*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*

- fixes #

#### Special notes for your reviewer

- .

#### Checklist

[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]

- [ ] Chart Version bumped
- [ ] Upgrading instructions are documented in the README.md

### CODE REVIEW

**Comment by mgruner** [comment]
@monotek not sure if I fully understand this correctly. But why do you think that `tmp/` needs to be shared in the cluster?

**Comment by monotek** [comment]
i saw some tmp related logs.
not sure if it helps. 
just testing.

**Comment by mgruner** [comment]
If you find something in `tmp/` that needs to be shared in the cluster, we need to look at it. Only `var/` should need to be shared at this point. 
Only local stuff should get written in `tmp/`.

**Comment by monotek** [comment]
I'll check for the error messages later. 
Have to work now...

**Pull request closed without merging**
