### PR TITLE
moving rails TMP into existing writable pvc and adding an init job to …

### LINKED ISSUE #205: Upload Failed Internal Server Error
**Version of Helm and Kubernetes**:

Kustomize Version: v4.5.4
Openshift Version: 4.12.25

**What happened**:

After uploading a file, I get :

> Upload Failed
> Internal Server Error

```
$ oc logs zammad-0
...
2023/07/27 07:29:07 [error] 7#7: *256 readv() failed (104: Connection reset by peer) while reading upstream, client: 10.138.12.1, server: _, request: "POST /api/v1/attachments HTTP/1.1", upstream: "http://[::1]:3000/api/v1/attachments", host: "zammad-zammad.apps.capc.muenchen.de", referrer: "http://zammad-zammad.apps.capc.muenchen.de/"
10.138.12.1 - - [27/Jul/2023:07:29:07 +0000] "POST /api/v1/attachments HTTP/1.1" 500 0 "http://zammad-zammad.apps.capc.muenchen.de/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:102.0) Gecko/20100101 Firefox/102.0"
10.138.26.1 - - [27/Jul/2023:07:29:17 +0000] "GET / HTTP/1.1" 200 2871 "-" "kube-probe/1.24"
...
$ oc logs zammad-0 -c zammad-railsserver
...
I, [2023-07-31T15:12:18.807076#1-112600]  INFO -- : Completed 200 OK in 22ms (Views: 1.6ms | ActiveRecord: 10.9ms | Allocations: 8997)
TMP is not writable: /opt/zammad/tmp
system temporary path is world-writable: /tmp
/tmp is world-writable: /tmp
. is not writable: /opt/zammad
2023-07-31 15:12:20 +0000 Rack app ("POST /api/v1/upload_caches/801359326" - (10.166.82.133, 10.138.12.1)): #<ArgumentError: could not find a temporary directory>
I, [2023-07-31T15:12:28.780556#1-112020]  INFO -- : Started GET "/" for ::ffff:10.138.22.1 at 2023-07-31 15:12:28 +0000

```

This happend with both Storage Mechanism, "filesystem" or "database".

**What you expected to happen**:

Successful upload.

### PR DESCRIPTION
**Pull request by klml**
…set permissions not world-writable #205

#### What this PR does / why we need it

cant upload files, using Openshift 

#### Which issue this PR fixes

- fixes #205

#### Special notes for your reviewer

It was not possible to use an simple empty dir, rails wants [a not world-writable](https://stackoverflow.com/questions/21117878/ruby-could-not-find-a-temporary-directory/31182540#31182540) directory.

So I added a new directory (`/opt/zammad/var/tmp`) 

* in the existing writable PVC to get Openshift satisfied to not write into the container, but in a PVC
* changed permissions to get rails satisfied to have a "not world-writable" directory.

Sadly I had to use an additional optional [init container](https://stackoverflow.com/questions/66857727/mounting-kubernetes-volume-with-user-permission), but tried to use the pattern from `data-chmod`.

The initcontainer `railsserver-tmp-init` is optional and default false, the only thing I changed in the existing statefulset is TMP directory to `/opt/zammad/var/tmp`.

I could use an helm var here, but I am not sure.

#### Checklist

- [x] Chart Version bumped
- [x] Upgrading instructions are documented in the README.md

### CODE REVIEW

**Review by monotek — CHANGES_REQUESTED** [review]
Thanks for working on this, as i'm realy busy at the moment.

I likely would reuse the already exisiting volume permissions init container:
https://github.com/zammad/zammad-helm/blob/main/zammad/templates/statefulset.yaml#L45C24-L45C41

The commands of your contaienr could just be added there.

**Comment by almarbjornsson** [comment]
Really interested in getting this working. We can't deploy until attachment upload is fixed

**Comment by klml** [comment]
> I likely would reuse the already exisiting volume permissions init container:
> The commands of your contaienr could just be added there.

My Problem is: in openshift I cant `chown /opt/zammad`, so I have to disable data-chmod and add this extra directory `/opt/zammad/var/tmp` and chmod this.
So imho it is either data-chmod or "my" railsserver-tmp-init.

I could try  to change the whole data-chmod and control it with some env or or the [configmap-init.yaml](https://github.com/zammad/zammad-helm/blob/main/zammad/templates/configmap-init.yaml)?
But imho we need an switch between `chown /opt/zammad` and `chmod /opt/zammad/var/tmp`.

**Comment by monotek** [comment]
I guess i would go for a configurable permission init container.
Maybe even make the command freely configurable?

**Comment by klml** [comment]
> Maybe even make the command freely configurable?

Now I am using the out-of-box [initContainers](https://github.com/zammad/zammad-helm/blob/main/zammad/values.yaml#L371), so I can add my `mkdir` and  `chmod` for rails.

The only thing I changed is the `.Values.zammadConfig.railsserver.tmpdir` to control the rails TMP Directory (the default `"/opt/zammad/tmp"` is not changed).

imho this is more noninvasive.

**Review by monotek — APPROVED** [review]

**Pull request merged**
