### PR TITLE
push chart to ghcr & update helm

### PR DESCRIPTION
**Pull request by monotek**
#### What this PR does / why we need it

- push chart to ghcr & update helm

#### Which issue this PR fixes

*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*

- fixes #

#### Special notes for your reviewer

- .

#### Checklist

[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]

- [ ] Chart Version bumped
- [ ] Upgrading instructions are documented in the README.md

### CODE REVIEW

**Comment by mgruner** [comment]
@monotek what about this one?

**Comment by monotek** [comment]
I could not olpush to this repos registry because of missing permissions 🤷‍♂️

Would be nice you could have a look?

The push in the other repo was a test. Needs cleanup too....

**Comment by monotek** [comment]
It's about docker push right for zammad/zammad-helm.
I can only push to zammad/zammad.

I also want to delete the following directories from zammad/zammad but I can't 🤷‍♂️


* https://github.com/zammad/zammad/pkgs/container/charts%2Fzammad/
* https://github.com/orgs/zammad/packages/container/package/zammad-helm%2Fzammad

**Comment by mgruner** [comment]
@monotek I deleted the two packages for you. Issue is that this requires `admin` privileges for zammad/zammad, which you do not have. That was because the packages referenced it as their image source repo.

For zammad-helm you do have `admin` rights, so pushing should work there (unless it's the same issue like mentioned above). Any suggestions?

**Comment by monotek** [comment]
Thanks, i'll try again later...

**Pull request merged**
