### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by mgruner**
#### What this PR does / why we need it

- Adds [updatecli](https://github.com/updatecli/updatecli) configuration to perform automated updates in future.

#### Checklist

- [x] Chart Version bumped

### CODE REVIEW

**Review by monotek — COMMENTED** [review]
Nice tool :)

Do you plan to automate this via the Github action too?
https://github.com/updatecli/updatecli-action

**Comment by mgruner** [comment]
> Nice tool :)
> 
> Do you plan to automate this via the Github action too? https://github.com/updatecli/updatecli-action

Not right now, but probably later on.

BTW I had to remove the upgrade testing again as there are issues with the low performance on default GitHub actions runners.

**Comment by mgruner** [comment]
@monotek I updated again to the latest Zammad patchlevel. This new image drops the unneeded node_modules folder, is thus much smaller and I hope the security scanner on artifacthub will find less stuff now.

**Comment by mueller-ma** [comment]
Did you have a look at https://docs.renovatebot.com/ ?  It detects the version automatically, so you don't have to define json patterns like `$.dependencies[0].version`, that may break in the future when new dependencies are added.
It's a GitHub app that creates PRs automatically.

**Comment by mgruner** [comment]
@monotek could you approve this please?

**Comment by mgruner** [comment]
@mueller-ma we use renovate for Zammad already, but not for the helm stuff yet. Do you have an example or documentation for this specific usage? I didn't find something useful yet.

**Comment by mueller-ma** [comment]
I use it in private repos, so I cannot share a link. But all you need is to enable Renovate for a repo and accept the onboarding PR. It supports subcharts (https://docs.renovatebot.com/modules/manager/helmv3/) and version in `values.yaml` files (https://docs.renovatebot.com/modules/manager/helm-values/).

**Pull request merged**
