### PR TITLE
remove hard-coded replica count and define antiAffinity for it

### PR DESCRIPTION
**Pull request by mskarbe**
#### What this PR does / why we need it:
The replica count of `zammad-*` pods was hardcoded to 1. The parameter `replicas` permits to set it without the need of patching the stateful set manually. 
Then, as well, it seemed to make sense to me to define default antiAffinity for it, so the pods would not be scheduled onto the same node.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md

### CODE REVIEW

**Comment by monotek** [comment]
How do you sync the files of the statefullset from one replica to the other?

**Comment by mskarbe** [comment]
@monotek, thank you for your response!
Can you please give me some insights about what kind of files you are referring to? I was not aware that there was any particular sync required, the understanding that I was provided with was that those were ElasticSearch data pods, that could be scaled without additional steps.
So do I suppose now correctly that it is deliberately allowed to have only one replica of this sts? Can I ask why?

**Comment by monotek** [comment]
Using several replicas of the containers would need them to have access to the same data but some data is stored in the filesystem, which is not shared between the containers.

This might give some more insight: https://github.com/zammad/zammad/issues/1601

**Comment by mskarbe** [comment]
@monotek, now it is clear! 
Thank you very much for explaining and sorry for unfitting PR. :)

**Comment by monotek** [comment]
It could work, if you use read write many storage calss, but as this is not so common we decided to better remove the option.

Maybe it makes sense to add it and add a warning, that you need special storage class to use it.

**Pull request closed without merging**
