### PR TITLE
Fixes: #275 - A fixed / well known label on init job.

### LINKED ISSUE #275: A fixed / well known label on init job
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): feature

Hi,

we are using [cilium](https://cilium.io/) to secure network communication within our infrastructure. After upgrading to the new 12.2 'deployments' chart we noticed there is an init job doing a lot of things.

Currently we are not able to specify a proper policy for the init job, as we are not able to 'pick' it by it's labels properly. There are only the common `app.kubernetes.io/name` / `app.kubernetes.io/instance` labels, that have all pods, and some autogenerated labes. But no labels like a `app.kubernetes.io/component: zammad-init` as we have it for all other pods.

Is it possible to add a label at https://github.com/zammad/zammad-helm/blob/main/zammad/templates/job-init.yaml#L28?

We would also welcome #259 as this would also help to tighten the connection between the deployment and the policies.

Thanks & Bye,
     Chris

### PR DESCRIPTION
**Pull request by mgruner**
#### Which issue this PR fixes

- fixes #275 

#### Checklist

- [x] Chart Version bumped

### CODE REVIEW

**Review by monotek — APPROVED** [review]

**Comment by mgruner** [comment]
@monotek sorry, I got it wrong first time and included the label in the configmap. It's now on the job and in the same way as for the deployments. 🤞

**Comment by monotek** [comment]
Whoops, missed that in the review too :D

As we're already on it.... 
It might be useful to have a configurable label here, like for the other pods too...

**Comment by mgruner** [comment]
> As we're already on it.... It might be useful to have a configurable label here, like for the other pods too...

Sorry, I don't get your point, can you explain please?

**Comment by monotek** [comment]
Sorry, my bad. 
Seems we only have configurable annotations right now and that also works for the init job.

I guess adding configurable labels per pod would be out of scope here.

**Review by monotek — APPROVED** [review]

**Pull request merged**
