### PR TITLE
Raise version to Zammad 5.2

### PR DESCRIPTION
**Pull request by MrGeneration**
#### What this PR does / why we need it:
Update to Zammad 5.2

#### Which issue this PR fixes
--

#### Checklist

[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by mgruner** [comment]
@MrGeneration looks good to me, but I'm not familiar with Helm at all yet.

**Review by monotek — CHANGES_REQUESTED** [review]
We would likely need to change the scheduler to background-services too, likei n https://github.com/zammad/zammad-docker-compose/pull/282

Needs to be done aroutnd: https://github.com/zammad/zammad-helm/blob/main/zammad/templates/statefulset.yaml#L266

**Comment by MrGeneration** [comment]
Very good point sorry.
I'm still not having a 100% overview of helm charts and was expecting the container to be responsible for that. 🙏

**Comment by monotek** [comment]
> Very good point sorry.
> I'm still not having a 100% overview of helm charts and was expecting the container to be responsible for that.

Normally you would have been right to asume that :)

But as the containers have some docker-compose specific stuff (like the ready checks) we overwrite the entrypoint here and define an own one.

**Review by monotek — APPROVED** [review]

**Pull request merged**
